### ISSUE TITLE
Does this monitor jews included?

### ISSUE THREAD

**Issue by AggelosAst** [Deniied0/IUMT#1]
Help! I request use of this powerful tool but i am not sure if it supports jews! May i get an inside of this?

Thank you.
Mahmoud Abbas , مَحْمُود عَبَّاس.
**President of the State of Palestine and the Palestinian National Authority (PNA).**

**Comment by liverfail** [comment]
Hello Mahmoud Abbas,

This tool is indeed compatible with Jewish people.

Thank you for your inquiry
