### ISSUE TITLE
Is this compatible with a Xi'an H-20 subsonic stealth bomber?

### ISSUE THREAD

**Issue by t0int1337** [Deniied0/IUMT#3]
Hi i want to implement this to my Xi'an H-20 subsonic stealth bomber, can you help me?

**Comment by liverfail** [comment]
Hello,

This is not for models, but rather games, simply add IUMT.lua as a script in ServerScriptService and IUMTL.lua as a localscript parented to it.

**Comment by t0int1337** [comment]
i can setup a http server for my Xi'an H-20
