### ISSUE TITLE
Hello! I have a strange issue which is about this not working.

### ISSUE THREAD

**Issue by richdentistboy** [Deniied0/IUMT#4]
I invited a **Jew** called _"Rinn"_ to my roblox game with this set up, and it didn't set his parent to nil??? Like, please fix it.

**Comment by t0int1337** [comment]
You cant set his parent to nil, this error occurs: Parent is not a valid member of Player "Players.Rinn"

**Comment by liverfail** [comment]
> I invited a **Jew** called _"Rinn"_ to my roblox game with this set up, and it didn't set his parent to nil??? Like, please fix it.

Hello, this tool is not compatible with New Jersey Jewish private school students, but rather Israeli indoctrinated civilians. My apologies for the inconvenience. However, it is not likely that this mentioned user will be in your game due to his legal threats from ROBLOX.
